### ISSUE TITLE
sometimes I get an error

### ISSUE THREAD

**Issue by catdad** [catdad/localcast#67]
When I leave the server running for a while -- often putting the computer to sleep and waking it back later -- I get an error. This seems to be new to the latest servercast feature, though I am not sure the error is related.

```
Error: write EOF
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:870:14)
```

```
Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:618:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' 
```

**Comment by catdad** [comment]
Another error:

```
unhandled err
Error: Device timeout
    at fn.ontimeout (D:\Git\chromecasts\node_modules\castv2-client\lib\senders\platform.js:56:26)
    at Object.onceWrapper (events.js:312:30)
    at emitNone (events.js:105:13)
    at fn.emit (events.js:207:7)
    at Timeout.ontimeout [as _onTimeout] (D:\Git\chromecasts\node_modules\castv2-client\lib\controllers\heartbeat.js:44:10)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
```

**Comment by catdad** [comment]
All done now, no more crashes.
