### ISSUE TITLE
chromecasts threw an error

### ISSUE THREAD

**Issue by catdad** [catdad/localcast#75]
![image](https://user-images.githubusercontent.com/2205537/45933743-e7b58a00-bf60-11e8-916e-6cb45fc8da62.png)

```
D:\Git\chromecasts\node_modules\castv2-client\lib\controllers\media.js:88
  data.mediaSessionId = this.currentSession.mediaSessionId;
                                            ^

TypeError: Cannot read property 'mediaSessionId' of null
    at fn.MediaController.sessionRequest (D:\Git\chromecasts\node_modules\castv2-client\lib\controllers\media.js:88:45)
    at fn.MediaController.stop (D:\Git\chromecasts\node_modules\castv2-client\lib\controllers\media.js:107:8)
    at DefaultMediaReceiver.stop (D:\Git\chromecasts\node_modules\castv2-client\lib\senders\default-media-receiver.js:42:19)
    at D:\Git\chromecasts\index.js:200:11
    at apply (D:\Git\chromecasts\node_modules\thunky\index.js:16:28)
    at D:\Git\chromecasts\node_modules\thunky\index.js:20:25
    at ready (D:\Git\chromecasts\index.js:108:11)
    at PlatformSender.join (D:\Git\chromecasts\node_modules\castv2-client\lib\senders\platform.js:88:3)
    at D:\Git\chromecasts\node_modules\castv2-client\lib\senders\platform.js:102:10
    at D:\Git\chromecasts\node_modules\castv2-client\lib\controllers\receiver.js:53:5
```

**Comment by catdad** [comment]
Duplicate of #76. Fixed.
